# config.yml

folder_names:
  silver_layer: "Layer_Silver"
  output_folder: "output"

paths:
  # This uses custom syntax we will parse in Python
  silver_layer_output_path: "${{ folder_names.silver_layer }}/${{ folder_names.output_folder }}"

dbt_project_dir: "datamarts_dbt"
dbt_output_filename: "layer_gold.db"