version: 2

sources:
  - name: silver_layer
    schema: main
    tables:
      - name: Dim_Member
      - name: Fact_Claims
      - name: Dim_Company
      - name: Dim_Provider
      - name: Dim_Policy
      - name: Dim_Member_Policies
      - name: Fact_Financial_Transactions