datamarts_dbt:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: main
      schema: main
      schemas_and_paths:
        # This maps the required 'main' schema to our dynamic source file
        main: "{{ env_var('DBT_SOURCE_FILE_PATH') }}"
      # This tells dbt where to create the output main.db file
      schema_directory: 'data'