[project]
name = "Layer_Gold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.10.9",
    "dbt-sqlite>=1.10.0",
    "pyyaml>=6.0.2",
]
