claimsDM_dbt:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'claims_datamart'
      schema: 'main'
      schemas_and_paths:
        main: '../../GenerateData/output/healthcare_oltp_20250817_2253.db'
      schema_directory: 'data'